server:
  port: 6050
  redis:
    #数据库索引
    database: 4
    #    host: 192.168.12.167
    #    port: 6379
    host: localhost
    port: 6379
    password:
    #连接超时时间
    timeout: 5000
logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
fontre:
  FileUrl: /Users/peng/Desktop/sphere.json